pipeline:
  identifier: Build_tfgenerator_1702449248834
  name: Build tfgenerator
  orgIdentifier: default
  projectIdentifier: Onboarding
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: org.Github
        repoName: tfgenerator
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: gobuild
                  name: go_build
                  spec:
                    connectorRef: account.Dockerhub
                    image: <+stage.variables.goBuildImage>
                    shell: Sh
                    command: go build
                  timeout: ""
                  type: Run
              - step:
                  identifier: gotest
                  name: go_test
                  spec:
                    connectorRef: account.Dockerhub
                    image: <+stage.variables.goBuildImage>
                    shell: Sh
                    command: go test -v ./...
                  timeout: ""
                  type: Run
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build and Push
                  identifier: Build_and_Push
                  spec:
                    connectorRef: account.Dockerhub
                    repo: mansong/tfgenerate
                    tags:
                      - latest
                    caching: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          caching:
            enabled: true
            paths: []
          slsa_provenance:
            enabled: false
        type: CI
        variables:
          - name: goBuildImage
            type: String
            description: ""
            required: false
            value: golang:1.21.5
        description: ""
